# Generated by Django 4.2.4 on 2023-08-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_rate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='cmnt_rate',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_rate',
            new_name='rate',
        ),
    ]
